export type IntelRow = {
  sheet_rank: number;
  student_low: number;
  student_high: number;
  student_count: number;
  fee_low: number;
  fee_high: number;
  average_fees: number;
  size_label: string;
  confidence: string;
  source: "published" | "estimate";
  note: string;
};

export const SCHOOL_INTEL: Record<string, IntelRow> = {
  "aggs, apo": {
    sheet_rank: 1,
    student_low: 700,
    student_high: 1200,
    student_count: 950,
    fee_low: 120000,
    fee_high: 250000,
    average_fees: 185000,
    size_label: "Very Large",
    confidence: "Medium",
    source: "estimate",
    note: "Public reporting confirms 150+ students in SS1 alone; current full enrolment/fees not publicly posted.",
  },
  "africa international college": {
    sheet_rank: 2,
    student_low: 600,
    student_high: 1000,
    student_count: 800,
    fee_low: 350000,
    fee_high: 500000,
    average_fees: 425000,
    size_label: "Very Large",
    confidence: "Higher confidence",
    source: "published",
    note: "Public sources confirm established secondary/primary institution; public fee figures vary by source/session.",
  },
  "creme quintessence school lokogoma": {
    sheet_rank: 3,
    student_low: 400,
    student_high: 700,
    student_count: 550,
    fee_low: 150000,
    fee_high: 300000,
    average_fees: 225000,
    size_label: "Large",
    confidence: "Medium",
    source: "estimate",
    note: "Public university report confirms a sizeable high-school cohort; current total enrolment/fees not published.",
  },
  "sterling model college, kubwa": {
    sheet_rank: 4,
    student_low: 250,
    student_high: 550,
    student_count: 400,
    fee_low: 100000,
    fee_high: 250000,
    average_fees: 175000,
    size_label: "Medium-Large",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "the winners joy int'l academy": {
    sheet_rank: 5,
    student_low: 300,
    student_high: 500,
    student_count: 400,
    fee_low: 80000,
    fee_high: 180000,
    average_fees: 130000,
    size_label: "Medium-Large",
    confidence: "Medium",
    source: "estimate",
    note: "Public school listing confirms active nursery/primary school; current enrolment not published.",
  },
  "advanced proficiency international school, apo": {
    sheet_rank: 6,
    student_low: 250,
    student_high: 450,
    student_count: 350,
    fee_low: 100000,
    fee_high: 200000,
    average_fees: 150000,
    size_label: "Medium-Large",
    confidence: "Low-Medium",
    source: "estimate",
    note: "Working estimate; current public enrolment/fee schedule not found.",
  },
  "ultimate trinity model school": {
    sheet_rank: 7,
    student_low: 250,
    student_high: 450,
    student_count: 350,
    fee_low: 70000,
    fee_high: 160000,
    average_fees: 115000,
    size_label: "Medium-Large",
    confidence: "Low-Medium",
    source: "estimate",
    note: "Working estimate; current public enrolment/fee schedule not found.",
  },
  "oasis college": {
    sheet_rank: 8,
    student_low: 200,
    student_high: 450,
    student_count: 325,
    fee_low: 80000,
    fee_high: 180000,
    average_fees: 130000,
    size_label: "Medium-Large",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "divine victorious leaders academy": {
    sheet_rank: 9,
    student_low: 200,
    student_high: 400,
    student_count: 300,
    fee_low: 50000,
    fee_high: 120000,
    average_fees: 85000,
    size_label: "Medium",
    confidence: "Low-Medium",
    source: "estimate",
    note: "Working estimate; current public enrolment/fee schedule not found.",
  },
  "winners' basic schools academy tasha 1 gwagwa abuja": {
    sheet_rank: 10,
    student_low: 200,
    student_high: 400,
    student_count: 300,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Medium",
    confidence: "Low-Medium",
    source: "estimate",
    note: "Working estimate; current public enrolment/fee schedule not found.",
  },
  "amagai international school, mpape abuja": {
    sheet_rank: 11,
    student_low: 180,
    student_high: 400,
    student_count: 290,
    fee_low: 70000,
    fee_high: 180000,
    average_fees: 125000,
    size_label: "Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "angelwings comprehensive college": {
    sheet_rank: 12,
    student_low: 180,
    student_high: 400,
    student_count: 290,
    fee_low: 70000,
    fee_high: 180000,
    average_fees: 125000,
    size_label: "Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "capstone foundational/high school": {
    sheet_rank: 13,
    student_low: 180,
    student_high: 400,
    student_count: 290,
    fee_low: 70000,
    fee_high: 180000,
    average_fees: 125000,
    size_label: "Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "claret international school": {
    sheet_rank: 14,
    student_low: 180,
    student_high: 400,
    student_count: 290,
    fee_low: 70000,
    fee_high: 180000,
    average_fees: 125000,
    size_label: "Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "cornerstone montessori schools": {
    sheet_rank: 15,
    student_low: 180,
    student_high: 400,
    student_count: 290,
    fee_low: 70000,
    fee_high: 180000,
    average_fees: 125000,
    size_label: "Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "emmado wellspring international school": {
    sheet_rank: 16,
    student_low: 180,
    student_high: 400,
    student_count: 290,
    fee_low: 70000,
    fee_high: 180000,
    average_fees: 125000,
    size_label: "Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "elegant gem nenamond schools": {
    sheet_rank: 17,
    student_low: 180,
    student_high: 400,
    student_count: 290,
    fee_low: 70000,
    fee_high: 180000,
    average_fees: 125000,
    size_label: "Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "fedland international schools ltd": {
    sheet_rank: 18,
    student_low: 180,
    student_high: 400,
    student_count: 290,
    fee_low: 70000,
    fee_high: 180000,
    average_fees: 125000,
    size_label: "Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "green pearls classic schools": {
    sheet_rank: 19,
    student_low: 180,
    student_high: 400,
    student_count: 290,
    fee_low: 70000,
    fee_high: 180000,
    average_fees: 125000,
    size_label: "Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "hephzibah international school": {
    sheet_rank: 20,
    student_low: 180,
    student_high: 400,
    student_count: 290,
    fee_low: 70000,
    fee_high: 180000,
    average_fees: 125000,
    size_label: "Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "juschearis schools": {
    sheet_rank: 21,
    student_low: 180,
    student_high: 400,
    student_count: 290,
    fee_low: 70000,
    fee_high: 180000,
    average_fees: 125000,
    size_label: "Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "mira-josh international school": {
    sheet_rank: 22,
    student_low: 180,
    student_high: 400,
    student_count: 290,
    fee_low: 70000,
    fee_high: 180000,
    average_fees: 125000,
    size_label: "Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "noble tribe international school sauka abuja": {
    sheet_rank: 23,
    student_low: 180,
    student_high: 400,
    student_count: 290,
    fee_low: 70000,
    fee_high: 180000,
    average_fees: 125000,
    size_label: "Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "precious kids model schools": {
    sheet_rank: 24,
    student_low: 180,
    student_high: 400,
    student_count: 290,
    fee_low: 70000,
    fee_high: 180000,
    average_fees: 125000,
    size_label: "Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "prized learners schools abuja": {
    sheet_rank: 25,
    student_low: 180,
    student_high: 400,
    student_count: 290,
    fee_low: 70000,
    fee_high: 180000,
    average_fees: 125000,
    size_label: "Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "questacumen international school kuje": {
    sheet_rank: 26,
    student_low: 180,
    student_high: 400,
    student_count: 290,
    fee_low: 70000,
    fee_high: 180000,
    average_fees: 125000,
    size_label: "Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "trinity care international school kuje": {
    sheet_rank: 27,
    student_low: 180,
    student_high: 400,
    student_count: 290,
    fee_low: 70000,
    fee_high: 180000,
    average_fees: 125000,
    size_label: "Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "first choice model academy": {
    sheet_rank: 28,
    student_low: 180,
    student_high: 350,
    student_count: 265,
    fee_low: 50000,
    fee_high: 120000,
    average_fees: 85000,
    size_label: "Medium",
    confidence: "Low-Medium",
    source: "estimate",
    note: "Public directory confirms FHA Lugbe nursery/primary school; current enrolment not published.",
  },
  "terrigem royal, jahi": {
    sheet_rank: 29,
    student_low: 150,
    student_high: 300,
    student_count: 225,
    fee_low: 80000,
    fee_high: 160000,
    average_fees: 120000,
    size_label: "Medium",
    confidence: "Low-Medium",
    source: "estimate",
    note: "Registered/active school evidence found; current enrolment/fees not publicly posted.",
  },
  "victory of god int'l academy, wanu apo": {
    sheet_rank: 30,
    student_low: 150,
    student_high: 300,
    student_count: 225,
    fee_low: 60000,
    fee_high: 140000,
    average_fees: 100000,
    size_label: "Medium",
    confidence: "Low-Medium",
    source: "estimate",
    note: "Working estimate; current public enrolment/fee schedule not found.",
  },
  "zuriel premier academy wumba": {
    sheet_rank: 31,
    student_low: 150,
    student_high: 300,
    student_count: 225,
    fee_low: 80000,
    fee_high: 160000,
    average_fees: 120000,
    size_label: "Medium",
    confidence: "Low-Medium",
    source: "estimate",
    note: "Public listing confirms nursery/primary school; current enrolment not published.",
  },
  "excellent mindset montessori int'l school, apo": {
    sheet_rank: 32,
    student_low: 120,
    student_high: 250,
    student_count: 185,
    fee_low: 60000,
    fee_high: 130000,
    average_fees: 95000,
    size_label: "Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate; current public enrolment/fee schedule not found.",
  },
  "unique school ltd": {
    sheet_rank: 33,
    student_low: 120,
    student_high: 250,
    student_count: 185,
    fee_low: 50000,
    fee_high: 120000,
    average_fees: 85000,
    size_label: "Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate; current public enrolment/fee schedule not found.",
  },
  "adorable stars model academy": {
    sheet_rank: 34,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "al falah international academy": {
    sheet_rank: 35,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "armorsville academy": {
    sheet_rank: 36,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "bistop academy": {
    sheet_rank: 37,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "bankys private school": {
    sheet_rank: 38,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 50000,
    fee_high: 150000,
    average_fees: 100000,
    size_label: "Medium",
    confidence: "Higher confidence",
    source: "published",
    note: "SchoolsCompass publishes ₦50k–₦150k/term; school site confirms nursery through senior high.",
  },
  "begin well academy dei dei": {
    sheet_rank: 39,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "brains & pens universal academy": {
    sheet_rank: 40,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "brimepp basic academy": {
    sheet_rank: 41,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "catering model academy": {
    sheet_rank: 42,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate; current public enrolment/fee schedule not found.",
  },
  "de- precious trust academy": {
    sheet_rank: 43,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "dieu est capable montessori academy": {
    sheet_rank: 44,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "evad stars academy": {
    sheet_rank: 45,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "everlasting king of kings academy lugbe-abuja": {
    sheet_rank: 46,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "explorers exceptional academy": {
    sheet_rank: 47,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "first divine favour science academy": {
    sheet_rank: 48,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "flourish academy": {
    sheet_rank: 49,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "foundation cornerstone academy": {
    sheet_rank: 50,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "fullmoon academy": {
    sheet_rank: 51,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "greater seeds richmaris academy": {
    sheet_rank: 52,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "horse gate academy": {
    sheet_rank: 53,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "joymon academy": {
    sheet_rank: 54,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "kellapraise international academy": {
    sheet_rank: 55,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "lebeni academy": {
    sheet_rank: 56,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "life line academy": {
    sheet_rank: 57,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "lordsbridge academy": {
    sheet_rank: 58,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "maplehill premier academy": {
    sheet_rank: 59,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "mercy seat stars academy": {
    sheet_rank: 60,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "noble honour academy": {
    sheet_rank: 61,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "olivia's haven academy": {
    sheet_rank: 62,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "rosa mystica academy": {
    sheet_rank: 63,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "roseville hall academy": {
    sheet_rank: 64,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "royal offspring academy": {
    sheet_rank: 65,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "salem academy": {
    sheet_rank: 66,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "st. olives multisensory academy": {
    sheet_rank: 67,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "stancharis intellectual academy": {
    sheet_rank: 68,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "trifold int'l academy": {
    sheet_rank: 69,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "the golden crest royal academy.": {
    sheet_rank: 70,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "the great children academy": {
    sheet_rank: 71,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "universal scholars academy": {
    sheet_rank: 72,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "vigad scholars academy": {
    sheet_rank: 73,
    student_low: 100,
    student_high: 250,
    student_count: 175,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "nspire school of management and technology": {
    sheet_rank: 74,
    student_low: 80,
    student_high: 250,
    student_count: 165,
    fee_low: 50000,
    fee_high: 150000,
    average_fees: 100000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "topkraft culinary academy": {
    sheet_rank: 75,
    student_low: 80,
    student_high: 250,
    student_count: 165,
    fee_low: 50000,
    fee_high: 150000,
    average_fees: 100000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "chessy kidies academy": {
    sheet_rank: 76,
    student_low: 100,
    student_high: 220,
    student_count: 160,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate; current public enrolment/fee schedule not found.",
  },
  "jeika premier academy": {
    sheet_rank: 77,
    student_low: 100,
    student_high: 220,
    student_count: 160,
    fee_low: 50000,
    fee_high: 120000,
    average_fees: 85000,
    size_label: "Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate; current public enrolment/fee schedule not found.",
  },
  "foundation of success nursery & primary school": {
    sheet_rank: 78,
    student_low: 100,
    student_high: 200,
    student_count: 150,
    fee_low: 40000,
    fee_high: 90000,
    average_fees: 65000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate; current public enrolment/fee schedule not found.",
  },
  "noble kiddies academy": {
    sheet_rank: 79,
    student_low: 80,
    student_high: 200,
    student_count: 140,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate; current public enrolment/fee schedule not found.",
  },
  "amitykids educational concept": {
    sheet_rank: 80,
    student_low: 80,
    student_high: 180,
    student_count: 130,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "cosa-big-g school bagusa": {
    sheet_rank: 81,
    student_low: 80,
    student_high: 180,
    student_count: 130,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "dafcom private school": {
    sheet_rank: 82,
    student_low: 80,
    student_high: 180,
    student_count: 130,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "dobbie school": {
    sheet_rank: 83,
    student_low: 80,
    student_high: 180,
    student_count: 130,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "emerald skyworth christian school": {
    sheet_rank: 84,
    student_low: 80,
    student_high: 180,
    student_count: 130,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "foundation of school nurs& pry school karu": {
    sheet_rank: 85,
    student_low: 80,
    student_high: 180,
    student_count: 130,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "gracious grace school, tasha 1 gwagwa abuja": {
    sheet_rank: 86,
    student_low: 80,
    student_high: 180,
    student_count: 130,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "his steps model school": {
    sheet_rank: 87,
    student_low: 80,
    student_high: 180,
    student_count: 130,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "holy child educational home": {
    sheet_rank: 88,
    student_low: 80,
    student_high: 180,
    student_count: 130,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "holy hill school": {
    sheet_rank: 89,
    student_low: 80,
    student_high: 180,
    student_count: 130,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "kazahchat": {
    sheet_rank: 90,
    student_low: 80,
    student_high: 180,
    student_count: 130,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "kingdom laureate school abuja": {
    sheet_rank: 91,
    student_low: 80,
    student_high: 180,
    student_count: 130,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "mercy blossom best bethel school": {
    sheet_rank: 92,
    student_low: 80,
    student_high: 180,
    student_count: 130,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "morning star glorious school kaba fct abuja": {
    sheet_rank: 93,
    student_low: 80,
    student_high: 180,
    student_count: 130,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "mustard seed private school": {
    sheet_rank: 94,
    student_low: 80,
    student_high: 180,
    student_count: 130,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "nigeria association of women journalists (nawoj)": {
    sheet_rank: 95,
    student_low: 80,
    student_high: 180,
    student_count: 130,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "noble kids bridge school": {
    sheet_rank: 96,
    student_low: 80,
    student_high: 180,
    student_count: 130,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "odyssey education foundation": {
    sheet_rank: 97,
    student_low: 80,
    student_high: 180,
    student_count: 130,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "peach potters intl": {
    sheet_rank: 98,
    student_low: 80,
    student_high: 180,
    student_count: 130,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "purple lilly int'l academy": {
    sheet_rank: 99,
    student_low: 80,
    student_high: 180,
    student_count: 130,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Corporate record found, but current operating status/fees should be verified.",
  },
  "rubyville school": {
    sheet_rank: 100,
    student_low: 80,
    student_high: 180,
    student_count: 130,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "st bartholomew's standard school, giri, abuja.": {
    sheet_rank: 101,
    student_low: 80,
    student_high: 180,
    student_count: 130,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "starlight private school, nyanya": {
    sheet_rank: 102,
    student_low: 80,
    student_high: 180,
    student_count: 130,
    fee_low: 40000,
    fee_high: 100000,
    average_fees: 70000,
    size_label: "Small-Medium",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "lofty height, pegi kuje": {
    sheet_rank: 103,
    student_low: 70,
    student_high: 180,
    student_count: 125,
    fee_low: 30000,
    fee_high: 80000,
    average_fees: 55000,
    size_label: "Small",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate; current public enrolment/fee schedule not found.",
  },
  "meganiel academy": {
    sheet_rank: 104,
    student_low: 70,
    student_high: 180,
    student_count: 125,
    fee_low: 30000,
    fee_high: 80000,
    average_fees: 55000,
    size_label: "Small",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate; current public enrolment/fee schedule not found.",
  },
  "great kiddies vision academy": {
    sheet_rank: 105,
    student_low: 60,
    student_high: 180,
    student_count: 120,
    fee_low: 30000,
    fee_high: 90000,
    average_fees: 60000,
    size_label: "Small",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "glory and able childcare academy": {
    sheet_rank: 106,
    student_low: 60,
    student_high: 180,
    student_count: 120,
    fee_low: 30000,
    fee_high: 90000,
    average_fees: 60000,
    size_label: "Small",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "tender babies school world": {
    sheet_rank: 107,
    student_low: 60,
    student_high: 180,
    student_count: 120,
    fee_low: 30000,
    fee_high: 90000,
    average_fees: 60000,
    size_label: "Small",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "tots academy abuja": {
    sheet_rank: 108,
    student_low: 60,
    student_high: 180,
    student_count: 120,
    fee_low: 30000,
    fee_high: 90000,
    average_fees: 60000,
    size_label: "Small",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate based on school type/name and Abuja private-school market; confirm directly.",
  },
  "triple divine int'l school": {
    sheet_rank: 109,
    student_low: 60,
    student_high: 150,
    student_count: 105,
    fee_low: 30000,
    fee_high: 80000,
    average_fees: 55000,
    size_label: "Small",
    confidence: "Low",
    source: "estimate",
    note: "Working estimate; current public enrolment/fee schedule not found.",
  },
};

