import { toE164Ng } from "@/lib/phones/e164";

export type RegistrationRow = {
  sn: number;
  proprietor_name: string;
  school_name: string;
  phone: string;
};

export const REGISTRATION_ROWS: RegistrationRow[] = [
  { sn: 1, proprietor_name: "Nkiruka Jesfransky Abba", school_name: "Gracious Grace School, Tasha 1 Gwagwa Abuja", phone: "8052117428" },
  { sn: 2, proprietor_name: "Barbara Onyebuenyi", school_name: "Adorable Stars Model Academy", phone: "8067759634" },
  { sn: 3, proprietor_name: "Caroline Yakubu", school_name: "Africa international college", phone: "8035901624" },
  { sn: 4, proprietor_name: "Busari Ismail Adewale", school_name: "Al Falah International Academy", phone: "8093945594" },
  { sn: 5, proprietor_name: "Sandra L.N Emmanuel", school_name: "Amagai International School, Mpape Abuja", phone: "8060312096" },
  { sn: 6, proprietor_name: "Suleiman Yunusa", school_name: "Amitykids Educational Concept", phone: "8036331416" },
  { sn: 7, proprietor_name: "Patience Edem Hogan", school_name: "AngelWings Comprehensive College", phone: "8036513400" },
  { sn: 8, proprietor_name: "Terhemen Aondoakaa", school_name: "Armorsville Academy", phone: "9039680147" },
  { sn: 9, proprietor_name: "olusola Bankole", school_name: "Bankys Private School", phone: "8023249880" },
  { sn: 10, proprietor_name: "EzekwesiIi Precious", school_name: "Begin Well Academy Dei Dei", phone: "8065682423" },
  { sn: 11, proprietor_name: "Obasanya Ibidun", school_name: "Brains & Pens Universal Academy", phone: "8030725756" },
  { sn: 12, proprietor_name: "Ada Oti Ukoha", school_name: "Brimepp Basic Academy", phone: "7035481949" },
  { sn: 13, proprietor_name: "Okafor chiamaka", school_name: "COSA-BIG-G SCHOOL BAGUSA", phone: "7034461952" },
  { sn: 14, proprietor_name: "Abimbola A Ojeifo", school_name: "Capstone Foundational/High School", phone: "8050980892" },
  { sn: 15, proprietor_name: "Tity Amosun Adebulehine", school_name: "Claret international school", phone: "8037881737" },
  { sn: 16, proprietor_name: "Bunmi Ola", school_name: "Cornerstone Montessori Schools", phone: "8035611356" },
  { sn: 17, proprietor_name: "Kelvin Okoduwa", school_name: "DAFCOM PRIVATE SCHOOL", phone: "8166851693" },
  { sn: 18, proprietor_name: "Adaku Okoduwa", school_name: "DAFCOM PRIVATE SCHOOL", phone: "8105187535" },
  { sn: 19, proprietor_name: "Okoduwa Kelvin", school_name: "DAFCOM PRIVATE SCHOOL", phone: "8166851693" },
  { sn: 20, proprietor_name: "Esther Eke", school_name: "DOBBIE SCHOOL", phone: "7037704567" },
  { sn: 21, proprietor_name: "Agbo precious", school_name: "De- Precious Trust Academy", phone: "8039567654" },
  { sn: 22, proprietor_name: "Helen Omojo Obiora", school_name: "Dieu Est Capable Montessori Academy", phone: "8060500714" },
  { sn: 23, proprietor_name: "Dorothy Ushie", school_name: "EMMADO WELLSPRING INTERNATIONAL SCHOOL", phone: "8036606493" },
  { sn: 24, proprietor_name: "Adhekegba E Monday", school_name: "Elegant Gem Nenamond Schools", phone: "9054025126" },
  { sn: 25, proprietor_name: "Saraya Ishaku-Gana", school_name: "Emerald Skyworth Christian School", phone: "8077744106" },
  { sn: 26, proprietor_name: "Obi Blessing", school_name: "Evad Stars Academy", phone: "9071976475" },
  { sn: 27, proprietor_name: "Obi Adaigwe Blessing", school_name: "Evad Stars Academy", phone: "9071976475" },
  { sn: 28, proprietor_name: "Dimkpa Christian Nathan", school_name: "Everlasting King of Kings Academy Lugbe-Abuja", phone: "8064035979" },
  { sn: 29, proprietor_name: "Briska Uzoka", school_name: "Explorers Exceptional Academy", phone: "8052738886" },
  { sn: 30, proprietor_name: "Francis Chijioke Obialaso", school_name: "Fedland International Schools Ltd", phone: "8034068562" },
  { sn: 31, proprietor_name: "Ihuioma Ijoma Zainab", school_name: "First Divine Favour Science Academy", phone: "8036042277" },
  { sn: 32, proprietor_name: "Ranti Adelegan", school_name: "Flourish Academy", phone: "8035307223" },
  { sn: 33, proprietor_name: "charles japheth", school_name: "Foundation Cornerstone Academy", phone: "8168460706" },
  { sn: 34, proprietor_name: "Nana Aishat Musa", school_name: "Fullmoon Academy", phone: "7067151344" },
  { sn: 35, proprietor_name: "Nwankwo Promise Sopuru", school_name: "GREAT KIDDIES VISION ACADEMY", phone: "8087346667" },
  { sn: 36, proprietor_name: "Charles c. Gloria", school_name: "Foundation Cornerstone Academy", phone: "8168460706" },
  { sn: 37, proprietor_name: "Hope Uzoigwe", school_name: "Glory and Able Childcare Academy", phone: "8025201353" },
  { sn: 38, proprietor_name: "Mary ndidiamaka nwaeze", school_name: "Greater seeds richmaris academy", phone: "8137854567" },
  { sn: 39, proprietor_name: "igunbode ayo", school_name: "Green Pearls Classic Schools", phone: "8097123681" },
  { sn: 40, proprietor_name: "Akukwe Eucharia", school_name: "HEPHZIBAH INTERNATIONAL SCHOOL", phone: "9013440486" },
  { sn: 41, proprietor_name: "Mrs Akukwe Eucharia Nwakaego", school_name: "HEPHZIBAH INTERNATIONAL SCHOOL", phone: "9013440486" },
  { sn: 42, proprietor_name: "Ogbu oyibo Margaret", school_name: "His steps model school", phone: "8039497769" },
  { sn: 43, proprietor_name: "Ajibike Alabi", school_name: "Holy Child Educational Home", phone: "8076296561" },
  { sn: 44, proprietor_name: "Helen Ehidiamhen", school_name: "Holy Hill School", phone: "8033010915" },
  { sn: 45, proprietor_name: "FOLASADE OLORUNDAMISI", school_name: "Horse Gate Academy", phone: "8038338477" },
  { sn: 46, proprietor_name: "Joy Monday", school_name: "Joymon academy", phone: "8062066570" },
  { sn: 47, proprietor_name: "Babatunde Bilikis Jummai", school_name: "Foundation of school nurs& pry school karu", phone: "8026505180" },
  { sn: 48, proprietor_name: "Osita Michael O", school_name: "Juschearis Schools", phone: "8038792166" },
  { sn: 49, proprietor_name: "Chidi Gift Kenechukwu", school_name: "Kazahchat", phone: "9128088622" },
  { sn: 50, proprietor_name: "Onah Nwobiyuma Ugbe", school_name: "Kellapraise International Academy", phone: "8055338069" },
  { sn: 51, proprietor_name: "Onah Emmanuella Ene", school_name: "Kellapraise International Academy", phone: "8022074942" },
  { sn: 52, proprietor_name: "", school_name: "Noble Kids Bridge School", phone: "7071738784" },
  { sn: 53, proprietor_name: "Faith Stephanie Itenebe", school_name: "Kingdom Laureate School Abuja", phone: "8036758250" },
  { sn: 54, proprietor_name: "Patience Ejiga", school_name: "Lebeni Academy", phone: "8064539372" },
  { sn: 55, proprietor_name: "Joseph Agbana", school_name: "Life Line Academy", phone: "8163372853" },
  { sn: 56, proprietor_name: "Dania Lawrence Omokogbo", school_name: "Lordsbridge Academy", phone: "8034963717" },
  { sn: 57, proprietor_name: "Oluwatosin Funmilola", school_name: "MapleHill Premier Academy", phone: "7051444438" },
  { sn: 58, proprietor_name: "Michael Victoria", school_name: "Mercy Blossom Best Bethel school", phone: "7062187293" },
  { sn: 59, proprietor_name: "ALLI omolola olamiotan", school_name: "Mercy seat stars academy", phone: "8100692705" },
  { sn: 60, proprietor_name: "Alli Omolola olamiotan", school_name: "Mercy seat stars academy", phone: "8100692705" },
  { sn: 61, proprietor_name: "Onwudike Godstime Chiedu", school_name: "Mira-Josh International School", phone: "8063004973" },
  { sn: 62, proprietor_name: "Igwe Chinonso. C.", school_name: "Morning Star glorious school Kaba FCT Abuja", phone: "7030481834" },
  { sn: 63, proprietor_name: "Priscilla Johnson", school_name: "Mustard seed private school", phone: "8036259509" },
  { sn: 64, proprietor_name: "Rebecca Bolanle Aluko Ukpevo", school_name: "Nigeria Association of Women Journalists (NAWOJ)", phone: "7038417065" },
  { sn: 65, proprietor_name: "Mrs Ikechukwu Blessing I.", school_name: "Noble Honour Academy", phone: "8032680499" },
  { sn: 66, proprietor_name: "Daniel Grace", school_name: "Noble Tribe International School sauka abuja", phone: "7064339001" },
  { sn: 67, proprietor_name: "Ishaq Akoji Alhassan", school_name: "Nspire school of Management and Technology", phone: "8025088851" },
  { sn: 68, proprietor_name: "AGINA FAITH EZZY FAITH", school_name: "OASIS COLLEGE", phone: "8037242247" },
  { sn: 69, proprietor_name: "Aretha Anokwurumadu", school_name: "Odyssey Education Foundation", phone: "8166460076" },
  { sn: 70, proprietor_name: "Ojo Titilayo. Olabisi", school_name: "BISTOP ACADEMY", phone: "8133663070" },
  { sn: 71, proprietor_name: "Princess Nkemdilim Nnaji", school_name: "Olivia's Haven Academy", phone: "8037862649" },
  { sn: 72, proprietor_name: "PRECIOUS E.NDEI", school_name: "PRECIOUS KIDS MODEL SCHOOLS", phone: "8068287802" },
  { sn: 73, proprietor_name: "Olawumi stella", school_name: "Peach potters Intl", phone: "8037872001" },
  { sn: 74, proprietor_name: "Chioma Chukwudile", school_name: "Prized Learners Schools Abuja", phone: "8033452203" },
  { sn: 75, proprietor_name: "Shade Esechie", school_name: "QUESTACUMEN INTERNATIONAL SCHOOL KUJE", phone: "8133881272" },
  { sn: 76, proprietor_name: "Juliana Olatunde", school_name: "Rosa Mystica Academy", phone: "8165499145" },
  { sn: 77, proprietor_name: "James Nkese Anne", school_name: "Roseville Hall Academy", phone: "7033621872" },
  { sn: 78, proprietor_name: "Chinyere KANU", school_name: "Royal Offspring Academy", phone: "8087645247" },
  { sn: 79, proprietor_name: "Eneje Sam-Shie", school_name: "Rubyville school", phone: "8023056380" },
  { sn: 80, proprietor_name: "Ruth Sam-Shie", school_name: "Rubyville school", phone: "8023056380" },
  { sn: 81, proprietor_name: "AUDU ALLI ABRAHAM", school_name: "SALEM ACADEMY", phone: "8187044410" },
  { sn: 82, proprietor_name: "OKUNLOLA SULAIMON OLAKUNLE", school_name: "STERLING MODEL COLLEGE, KUBWA", phone: "8033736278" },
  { sn: 83, proprietor_name: "Ven. Babatunde Owolana", school_name: "St Bartholomew's Standard School, Giri, Abuja.", phone: "8056882810" },
  { sn: 84, proprietor_name: "Okwechime Patience", school_name: "St. Olives Multisensory Academy", phone: "8037985827" },
  { sn: 85, proprietor_name: "Okwechime Patience Agatha", school_name: "St. Olives Multisensory Academy", phone: "8037985827" },
  { sn: 86, proprietor_name: "Iheanetu Uchenna Stanislaus", school_name: "Stancharis Intellectual Academy", phone: "9021723533" },
  { sn: 87, proprietor_name: "Charity chikodi uchenna", school_name: "Stancharis Intellectual academy", phone: "7065796183" },
  { sn: 88, proprietor_name: "Mrs Helen Ukpong-Neto.", school_name: "Starlight Private School, Nyanya", phone: "7080712636" },
  { sn: 89, proprietor_name: "Mrs Ukpong-Neto Helen", school_name: "Starlight Private School, Nyanya", phone: "7080712636" },
  { sn: 90, proprietor_name: "Oluwayemisi S. Adeyemi", school_name: "TRIFOLD INT'L ACADEMY", phone: "8035968796" },
  { sn: 91, proprietor_name: "ATO LOVETH AUMBUR", school_name: "TRINITY CARE INTERNATIONAL SCHOOL KUJE", phone: "7063395990" },
  { sn: 92, proprietor_name: "Akpoezi Juliet Efih", school_name: "Tender Babies School World", phone: "8038624250" },
  { sn: 93, proprietor_name: "Emmanuella Afoke oneju", school_name: "Tender Babies School World", phone: "8035244177" },
  { sn: 94, proprietor_name: "Dr Unenwojo Sarah Edah.", school_name: "The Golden Crest Royal Academy.", phone: "8135381988" },
  { sn: 95, proprietor_name: "Princess maduka", school_name: "The great children Academy", phone: "8106939556" },
  { sn: 96, proprietor_name: "Hellen Tolulope Olusola", school_name: "Topkraft Culinary Academy", phone: "8021257455" },
  { sn: 97, proprietor_name: "Temitope R. Adebanjo", school_name: "Tots Academy Abuja", phone: "8023750528" },
  { sn: 98, proprietor_name: "Scholastica Arizet", school_name: "Ultimate trinity model school", phone: "8147776673" },
  { sn: 99, proprietor_name: "Ada Agenyi Jesse", school_name: "Unique School Ltd", phone: "8059663890" },
  { sn: 100, proprietor_name: "Clementine Sanya", school_name: "Universal Scholars Academy", phone: "9066954125" },
  { sn: 101, proprietor_name: "Okeke chiamaka Juliet", school_name: "Vigad scholars Academy", phone: "8034179120" },
  { sn: 102, proprietor_name: "Prof Eleazar Uruakpa", school_name: "Winners' Basic Schools Academy Tasha 1 Gwagwa Abuja", phone: "7038968827" },
  { sn: 103, proprietor_name: "Tokunbo Adebisi", school_name: "Zuriel Premier Academy Wumba", phone: "8037861901" },
  { sn: 104, proprietor_name: "Nwosu Hope", school_name: "Divine victorious leaders academy", phone: "8035900824" },
];

export function seedId(sn: number): string {
  return `reg-${sn}`;
}

export function asSeedInput(row: RegistrationRow) {
  return {
    school_name: row.school_name,
    proprietor_name: row.proprietor_name.trim() || null,
    phone: toE164Ng(row.phone),
    notes: null,
    contact_person: null,
    status: "not_yet_contacted" as const,
  };
}
